apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "payment-gateway.fullname" . }}
  labels:
    {{- include "payment-gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ include "payment-gateway.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "payment-gateway.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 10s }
        - setWeight: 50
        - pause: { duration: 10s }
        - setWeight: 100
        - pause: { duration: 10s }

