apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}

